//{{NO_DEPENDENCIES}}
// App Studio generated include file.
// Used by RESOURCE.RC
//
#define IDI_APPICON                     100
#define IDR_ACCELERATOR                 101
#define IDD_MAINDIALOG                  102
#define IDD_ABOUTDIALOG                 103
#define IDR_APPMENU                     104
#define IDD_CONNMANDIALOG               105
#define IDD_ENTERTEXTDIALOG             106
#define IDD_PROFILESTGSDIALOG           107
#define IDD_PROFILESETTINGSDIALOG       107
#define IDD_PMAIN_STGSPAGE              108
#define IDD_PCONN_STGSPAGE              109
#define ID_HELP_ABOUT                   200
#define ID_CONNECT                      201
#define ID_QUIT                         202
#define ID_ABOUT                        204
#define ID_NEW_PROFILE                  205
#define ID_OPEN_PROFILE                 207
#define ID_EDIT_PROFILE                 208
#define ID_DELETE_PROFILE               209
#define IDC_MSGINPUT                    1002
#define IDC_MSGINPUT_EDIT               1002
#define IDC_EDIT2                       1003
#define IDC_MSG_EDIT                    1003
#define IDC_SENDBTN                     1004
#define IDC_SENDMSG_BTN                 1004
#define IDC_CORYRIGHT                   1005
#define IDC_PROFILELIST                 1007
#define IDC_CREATE_PROFILE_BTN          1008
#define IDC_CONNECT_BTN                 1009
#define IDC_EDIT_PROFILE_BTN            1010
#define IDC_ENTERTEXTLABEL              1010
#define IDC_DELETE_PROFILE_BTN          1011
#define IDC_ENTERTEXTBOX                1011
#define IDC_PROFILES_GROUP              1012
#define IDC_APPNAME                     1013
#define IDC_GITHUB_LINK                 1014
#define IDC_COMBO1                      1015
#define IDC_PAGESCOMBO                  1015
#define IDC_PAGE_LABEL                  1016
#define IDC_PROFILE_NAME_LABEL          1018
#define IDC_PROFILE_NAME_EDIT           1019
#define IDC_NICKNAME_LABEL              1020
#define IDC_PROFILE_SERVER_LABEL        1020
#define IDC_NICKNAMES_LABEL             1020
#define IDC_NICKNAME_EDIT               1021
#define IDC_PROFILE_SERVER_EDIT         1021
#define IDC_NICKNAMES_EDIT              1021
#define IDC_PASSWORD_LABEL              1022
#define IDC_PROFILE_PORT_LABEL          1022
#define IDC_PASSWORD_EDIT               1023
#define IDC_PROFILE_PORT_EDIT           1023
#define IDC_REALNAME_LABEL              1024
#define IDC_REALNAME_EDIT               1025
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS

#define _APS_NEXT_RESOURCE_VALUE        110
#define _APS_NEXT_COMMAND_VALUE         210
#define _APS_NEXT_CONTROL_VALUE         1022
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
